name: "osmi-smartsim-cloudmesh"

ee:
  time: "0:30:00"

description: "SmartSim on Ubuntu with Docker" 

submission:
  benchmark: {name}
  name: {name}
  submitter: Gregor von Laszewski
  email: laszewski@gmail.com
  org: University of Virginia
  division: open
  version: 1.0
  github_commit_version: TBD
  status: completed
  platform: rivanna
  accelerators_per_node: 1

experiment:
  #arch: "small_lstm,medium_cnn,large_tcnn"
  arch: "small_lstm"
  samples: 100
  epochs: 5
  batch_size: 1
  requests: 128
  directive: "a100"
  #directive: "a100,a100-dgx,v100,rtx2080,rtx3090,a100-pod,a6000"
  #directive: "k80,p100"
  #directive: "ubuntu"
  repeat: "1"
  #repeat: "1,2,3,4,5,6,7,8,9,10"
  #directive: "a100-dgx,a6000"
  #directive: "a100,v100,rtx2080,rtx3090,a100-pod"
  #directive: "a6000"
  #repeat: "1"
  batch_requests: True
  replicas: 1
  num_gpus: 1
  # device: "cuda,cpu"
  device: "cuda"

time:
  small_lstm: 5
  medium_cnn: 30
  large_tcnn: 60

identifier: "{experiment.directive}_{experiment.arch}-{experiment.repeat}"

system:
  host: "rivanna"
  python: "3.11.8"
  num_cpus: 1
  platform: rivanna
  accelerators_per_node: 1
  constraint: ""
  reservation: ""

output:
  directory: "./project/model_{experiment.arch}_directive_{experiment.directive}_repeat_{experiment.repeat}"

